/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrafficRouteImport } from './routes/traffic'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SimulationsRouteImport } from './routes/simulations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as EnvironmentRouteImport } from './routes/environment'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as IndexRouteImport } from './routes/index'

const TrafficRoute = TrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsRoute = SimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRoute = EnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/environment': typeof EnvironmentRoute
  '/infrastructure': typeof InfrastructureRoute
  '/settings': typeof SettingsRoute
  '/simulations': typeof SimulationsRoute
  '/sustainability': typeof SustainabilityRoute
  '/timeline': typeof TimelineRoute
  '/traffic': typeof TrafficRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/environment': typeof EnvironmentRoute
  '/infrastructure': typeof InfrastructureRoute
  '/settings': typeof SettingsRoute
  '/simulations': typeof SimulationsRoute
  '/sustainability': typeof SustainabilityRoute
  '/timeline': typeof TimelineRoute
  '/traffic': typeof TrafficRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/environment': typeof EnvironmentRoute
  '/infrastructure': typeof InfrastructureRoute
  '/settings': typeof SettingsRoute
  '/simulations': typeof SimulationsRoute
  '/sustainability': typeof SustainabilityRoute
  '/timeline': typeof TimelineRoute
  '/traffic': typeof TrafficRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/digital-twin'
    | '/environment'
    | '/infrastructure'
    | '/settings'
    | '/simulations'
    | '/sustainability'
    | '/timeline'
    | '/traffic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/digital-twin'
    | '/environment'
    | '/infrastructure'
    | '/settings'
    | '/simulations'
    | '/sustainability'
    | '/timeline'
    | '/traffic'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/digital-twin'
    | '/environment'
    | '/infrastructure'
    | '/settings'
    | '/simulations'
    | '/sustainability'
    | '/timeline'
    | '/traffic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  EnvironmentRoute: typeof EnvironmentRoute
  InfrastructureRoute: typeof InfrastructureRoute
  SettingsRoute: typeof SettingsRoute
  SimulationsRoute: typeof SimulationsRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TimelineRoute: typeof TimelineRoute
  TrafficRoute: typeof TrafficRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traffic': {
      id: '/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof TrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations': {
      id: '/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof SimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment': {
      id: '/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  EnvironmentRoute: EnvironmentRoute,
  InfrastructureRoute: InfrastructureRoute,
  SettingsRoute: SettingsRoute,
  SimulationsRoute: SimulationsRoute,
  SustainabilityRoute: SustainabilityRoute,
  TimelineRoute: TimelineRoute,
  TrafficRoute: TrafficRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
